# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.6'

    - name: Build for x86
      run: go build -v -o boulder-bot_x86 .

    - name: Test
      run: go test -v .

    - name: Build for ARM 64
      run: env GOOS=linux GOARCH=arm64 go build -v -o boulder-bot_arm64 .

    - name: Build for ARM 
      run: env GOOS=linux GOARCH=arm go build -v -o boulder-bot_arm .

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.2.0
      with:
        name: boulder-bot_${{ github.sha }}
        path: |
          /home/runner/work/boulder-bot/boulder-bot/boulder-bot_x86
          /home/runner/work/boulder-bot/boulder-bot/boulder-bot_arm64
          /home/runner/work/boulder-bot/boulder-bot/boulder-bot_arm
          /home/runner/work/boulder-bot/boulder-bot/boulder-bot.service
          /home/runner/work/boulder-bot/boulder-bot/install.sh
          /home/runner/work/boulder-bot/boulder-bot/uninstall.sh
